[package]
name = "bevy_silk"
version = "0.1.0"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
repository = "https://github.com/ManevilleF/bevy_silk"
license-file = "./LICENSE"
exclude = ["docs", "assets", ".github"]
description = "Cloth physics implementation in bevy"
keywords = ["verlet", "physics", "bevy", "cloth"]
categories = ["game-engines", "game-development"]
readme = "README.md"
documentation = "https://docs.rs/bevy_silk"

[features]
default = []
debug = ["bevy-inspector-egui", "bevy"]

[dependencies]

# Bevy dependencies
bevy_app = "0.7"
bevy_utils = "0.7"
bevy_ecs = "0.7"
bevy_render = "0.7"
bevy_math = "0.7"
bevy_log = "0.7"
bevy_transform = "0.7"
bevy_core = "0.7"
bevy_asset = "0.7"
bevy_reflect = "0.7"

# Error handling
thiserror = "1.0"

[dependencies.bevy-inspector-egui]
version = "0.11"
optional = true

[dependencies.bevy]
version = "0.7"
optional = true
default-features = false

[dev-dependencies]
smooth-bevy-cameras = "0.4"
bevy-inspector-egui = "0.11"

[dev-dependencies.bevy]
version = "0.7"
features = ["render", "bevy_winit", "x11", "png"]
default-features = false

[[example]]
name = "balloon_example"
required-features = ["debug"]

[[example]]
name = "flag_example"
required-features = ["debug"]

[[example]]
name = "moving_example"
required-features = ["debug"]