[package]
name = "bevy_silk"
version = "0.1.0"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
repository = "https://github.com/ManevilleF/bevy_silk"
license-file = "./LICENSE"
exclude = ["docs", "assets", ".github"]
description = "Cloth physics implementation in bevy"
keywords = ["verlet", "physics", "bevy", "cloth"]
categories = ["game-engines", "game-development"]
readme = "README.md"
documentation = "https://docs.rs/bevy_silk"

[features]
default = []
debug = ["bevy-inspector-egui"]
rapier_collisions = ["bevy_rapier3d"]

[dependencies]

# Error handling
thiserror = "1.0"

[dependencies.bevy-inspector-egui]
version = "0.11"
optional = true

[dependencies.bevy]
version = "0.7"
default-features = false
features = ["bevy_render"]

[dependencies.bevy_rapier3d]
version = "0.13"
optional = true
default-features = false
features = ["dim3"]

[dev-dependencies]
smooth-bevy-cameras = "0.4"
bevy-inspector-egui = "0.11"

[dev-dependencies.bevy]
version = "0.7"
features = ["render", "bevy_winit", "x11", "png"]
default-features = false

[[example]]
name = "balloon_example"
required-features = ["debug"]

[[example]]
name = "flag_example"
required-features = ["debug"]

[[example]]
name = "moving_example"
required-features = ["debug"]

[[example]]
name = "collision_example"
required-features = ["debug", "rapier_collisions"]